{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Dev Logs",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service-dev\"} | json"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "count by() (user_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP requests / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    { "expr": "irate(request_total[1m])", "legendFormat": "__auto" },
    { "expr": "irate(request_get[1m])", "legendFormat": "__auto" },
    { "expr": "irate(request_post[1m])", "legendFormat": "__auto" },
    { "expr": "irate(request_delete[1m])", "legendFormat": "__auto" },
    { "expr": "irate(request_put[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    { "expr": "revenue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth Requests /min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "expr": "irate(auth_success[1m])", "legendFormat": "__auto" },
    { "expr": "irate(auth_failure[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Purchases / min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "expr": "irate(order_success[1m])", "legendFormat": "__auto" },
    { "expr": "irate(order_failure[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_CPU", "legendFormat": "__auto" },
    { "expr": "system_memory", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "latency_orders", "legendFormat": "__auto" },
    { "expr": "latency_general", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} | json"
    }
   ]
  }
 ]
}